# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [3]:
arr=np.array([1,1,1,1,1,1,1,1,1,1])

#### Create an array of 10 fives

In [4]:
arr=np.array([5,5,5,5,5,5,5,5,5,5])

#### Create an array of the integers from 10 to 50

In [9]:
arr=np.arange(10,51)

#### Create an array of all the even integers from 10 to 50

In [13]:
arr=np.arange(10,51,2)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
arr=np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])

#### Create a 3x3 identity matrix

In [18]:
arr=np.array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [22]:
x=np.random.rand()

In [23]:
random_number = np.random.rand()
random_number

0.7197653011127091

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [28]:
arr=np.random.randn(25)

#### Create the following matrix:

In [31]:
arr=np.arange(0.01,1.01,0.01).reshape(10,10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [32]:
arr=np.linspace(0,1,20)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [36]:
arr=np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [47]:
print(arr[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [45]:
print(arr[3,4])

20


In [48]:
print(arr[:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [50]:
print(arr[4,:5])

[21 22 23 24 25]


In [51]:
print(arr[3:5,:5])

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!